### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by zzmingo** [caoxiemeihao/electron-vite-react#22]
```javascript
const M = require("url");

export default M;

export const Url = M.Url;
export const parse = M.parse;
export const resolve = M.resolve;
export const resolveObject = M.resolveObject;
export const format = M.format;
export const URL = M.URL;
export const URLSearchParams = M.URLSearchParams;
export const domainToASCII = M.domainToASCII;
export const domainToUnicode = M.domainToUnicode;
export const pathToFileURL = M.pathToFileURL;
export const fileURLToPath = M.fileURLToPath;
export const urlToHttpOptions = M.urlToHttpOptions;
```

![image](https://user-images.githubusercontent.com/24818119/159157562-e844a351-a8d9-48b2-928b-fc3ba7f3da82.png)

**Comment by zzmingo** [comment]
追加几个问题：

开了 nodeIntegration，去掉了 resolveElectron

```
index.js:11 Uncaught TypeError: Cannot read properties of undefined (reading 'from')
    at node_modules/safe-buffer/index.js (index.js:11:12)
```

改vite配置（其实没改就保存了一下）重启后
```
node:internal/modules/cjs/loader:940 Uncaught Error: Cannot find module './cjs/react-jsx-runtime.production.min.js'
```

去掉 resolveElectron 的原因是：
```
node:internal/modules/cjs/loader:940 Uncaught Error: Cannot find module 'buffer/'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.o._resolveFilename (node:electron/js2c/renderer_init:33:1095)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Function.o._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at BrowserPlatformTools.ts:168:21
```

**Comment by caoxiemeihao** [comment]
你看下这个 issues 是否能给你提供一些思路
[请教一下vite-renderer.config中的resolveElectron函数](https://github.com/caoxiemeihao/electron-vite-vue/issues/52)
